/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg251.project;

import com.mysql.jdbc.Connection;
import static java.lang.Math.random;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author leo0x
 */
public class Menuandcart extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    String user;

    public Menuandcart() {
        initComponents();
    }

    public Menuandcart(String val) {
        initComponents();
        this.user = val;

    }

    //single beef burger
    int bsingle = 0;
    double bsingleprice = 12.0;
    double btotal = 0;

    //double beef burger
    int bdouble = 0;
    double bdoubleprice = 16.0;
    double bdoubletotal = 0;

    //Chicken Burger
    int chickenburger = 0;
    double chickenprice = 13.0;
    double chickentotal = 0;

    //chicken deluxe
    int chickenburgerdeluxe = 0;
    double chickendeluxeprice = 18.0;
    double chickendeluxetotal = 0;
    double total = 0;

    int orders = (int) (Math.abs(random() * 100));

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        plusbeef = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minusbeef = new javax.swing.JButton();
        Addtocart1 = new javax.swing.JButton();
        singlebeef = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        minusdoublebeef = new javax.swing.JButton();
        plusdoublebeef = new javax.swing.JButton();
        doublebeefnum = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        minuschicken = new javax.swing.JButton();
        chicken = new javax.swing.JLabel();
        pluschicken = new javax.swing.JButton();
        minuschickendelux = new javax.swing.JButton();
        chickendelux = new javax.swing.JLabel();
        pluschickendelux = new javax.swing.JButton();
        Addtocart2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        beef = new javax.swing.JLabel();
        paynow = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doublebeef = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalview = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        chik = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        chikdelux = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plusbeef.setText("+");
        plusbeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusbeefActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\leo0x\\Documents\\NetBeansProjects\\251-project\\Beefsingle.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setText("Beef Burger");

        minusbeef.setText("-");
        minusbeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusbeefActionPerformed(evt);
            }
        });

        Addtocart1.setText("Add to cart");
        Addtocart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addtocart1ActionPerformed(evt);
            }
        });

        singlebeef.setBackground(new java.awt.Color(69, 217, 217));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\leo0x\\Documents\\NetBeansProjects\\251-project\\beefdouble.jpg")); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setText("Double Beef Burger");

        minusdoublebeef.setText("-");
        minusdoublebeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusdoublebeefActionPerformed(evt);
            }
        });

        plusdoublebeef.setText("+");
        plusdoublebeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusdoublebeefActionPerformed(evt);
            }
        });

        doublebeefnum.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minusdoublebeef, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(doublebeefnum, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(plusdoublebeef, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(71, 71, 71))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                        .addComponent(minusbeef, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(singlebeef, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(plusbeef, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(Addtocart1)
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minusbeef)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(singlebeef, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plusbeef))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Addtocart1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusdoublebeef)
                    .addComponent(plusdoublebeef)
                    .addComponent(doublebeefnum))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(26, 104, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Beef", jPanel1);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\leo0x\\Documents\\NetBeansProjects\\251-project\\chicken burger.jpg")); // NOI18N
        jLabel9.setText("jLabel9");

        jLabel10.setText("Chicken Burger");

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\leo0x\\Documents\\NetBeansProjects\\251-project\\chicken burger deluxe.jpg")); // NOI18N
        jLabel11.setText("jLabel11");

        jLabel12.setText("Chicken Deluxe");

        minuschicken.setText("-");
        minuschicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minuschickenActionPerformed(evt);
            }
        });

        chicken.setText(" ");

        pluschicken.setText("+");
        pluschicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pluschickenActionPerformed(evt);
            }
        });

        minuschickendelux.setText("-");
        minuschickendelux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minuschickendeluxActionPerformed(evt);
            }
        });

        chickendelux.setText(" ");

        pluschickendelux.setText("+");
        pluschickendelux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pluschickendeluxActionPerformed(evt);
            }
        });

        Addtocart2.setText("Add to cart");
        Addtocart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Addtocart2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minuschicken, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minuschickendelux, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chicken, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chickendelux, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pluschickendelux)
                            .addComponent(pluschicken))
                        .addContainerGap(134, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Addtocart2)
                        .addGap(25, 25, 25))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(Addtocart2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minuschickendelux)
                            .addComponent(chickendelux)
                            .addComponent(pluschickendelux)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(minuschicken)
                            .addComponent(chicken)
                            .addComponent(pluschicken))))
                .addGap(33, 33, 33)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chicken", jPanel2);

        paynow.setText("Finish order");
        paynow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paynowActionPerformed(evt);
            }
        });

        jLabel4.setText("Number of beef burgers: ");

        jLabel6.setText("Number of double beef burger: ");

        jLabel3.setText("Total");

        totalview.setText(" ");

        jLabel13.setText("Number of Chicken burger:");

        jLabel14.setText("Number of Chicken deluxe");

        chik.setText(" ");

        chikdelux.setText(" ");

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(beef, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14)
                                            .addComponent(Reset))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(doublebeef, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(chik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(chikdelux, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalview, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paynow)))
                .addGap(82, 82, 82))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doublebeef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(chik))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(chikdelux))
                .addGap(51, 51, 51)
                .addComponent(Reset)
                .addGap(77, 77, 77)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalview))
                .addGap(36, 36, 36)
                .addComponent(paynow)
                .addGap(86, 86, 86))
        );

        jTabbedPane1.addTab("Cart", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String us="";
    public void setUser(String u){
this.us = u;
}
    private void paynowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paynowActionPerformed

        String sql = " insert into orders (user,ordernumber,numofsinglebeef,numberofdoublebeef,numOfchicken,Numofdulxe,total) values(?,?,?,?,?,?,?)";
        Loginscreen po = new Loginscreen();

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/cpit-251?autoReconnect=true&useSSL=false", "root", "");

            PreparedStatement pstmt = conn.prepareStatement(sql);
            Loginscreen l = new Loginscreen();

            pstmt.setString(1,us);

            pstmt.setInt(2, orders);

            pstmt.setInt(3, bsingle);

            pstmt.setInt(4, bdouble);
            pstmt.setInt(5, chickenburger);
            pstmt.setInt(6, chickenburgerdeluxe);
            total = (btotal + bdoubletotal + chickentotal + chickendeluxetotal);
            pstmt.setDouble(7, total);

            pstmt.execute();

            JOptionPane.showMessageDialog(null, "Your Order is:,\n"
                    + " you order number is: " + orders
                    + "\n Number of Beef Burgers:  " + bsingle + "    Pirce: " + (btotal = database.Mutli(bsingle, (int) bsingleprice))
                    + "\n Number of Double Beef Burgers: " + bdouble + "   Price : " + (bdoubletotal = database.Mutli(bdouble, (int) bdoubleprice))
                    + "\n Number of Chicken Burgers: " + chickenburger + "   Price : " + (chickentotal = database.Mutli(chickenburger, (int) chickenprice))
                    + "\n Number of deluxe Burgers: " + chickenburgerdeluxe + "   Price : " + (chickendeluxetotal = database.Mutli(chickenburgerdeluxe, (int) chickendeluxeprice))
                    + "\n Total:  " + (btotal + bdoubletotal + chickentotal + chickendeluxetotal
                    + "\n User" + us)
            );

            beef.setText(" " + bsingle + "    Pirce: " + (btotal = database.Mutli(bsingle, (int) bsingleprice)));

            doublebeef.setText(" " + bdouble + "   Price : " + (bdoubletotal = database.Mutli(bdouble, (int) bdoubleprice)));

            chik.setText(" " + chickenburger + "   Price : " + (chickentotal = database.Mutli(chickenburger, (int) chickenprice)));

            chikdelux.setText(" " + chickenburgerdeluxe + "   Price : " + (chickendeluxetotal = database.Mutli(chickenburgerdeluxe, (int) chickendeluxeprice)));
            dispose();

            po.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_paynowActionPerformed

    private void Addtocart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addtocart2ActionPerformed

        beef.setText(" " + bsingle + "    Pirce: " + (btotal = database.Mutli(bsingle, (int) bsingleprice)));

        doublebeef.setText(" " + bdouble + "   Price : " + (bdoubletotal = database.Mutli(bdouble, (int) bdoubleprice)));

        chik.setText(" " + chickenburger + "   Price : " + (chickentotal = database.Mutli(chickenburger, (int) chickenprice)));

        chikdelux.setText(" " + chickenburgerdeluxe + "   Price : " + (chickendeluxetotal = database.Mutli(chickenburgerdeluxe, (int) chickendeluxeprice)));
        totalview.setText(" " + (btotal + bdoubletotal + chickentotal + chickendeluxetotal));

        JOptionPane.showMessageDialog(null, "Items added to cart   ");
    }//GEN-LAST:event_Addtocart2ActionPerformed

    private void pluschickendeluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pluschickendeluxActionPerformed

        chickenburgerdeluxe++;

        chickendelux.setText(" " + chickenburgerdeluxe + "   Price : " + (chickendeluxetotal = database.Mutli(chickenburgerdeluxe, (int) chickendeluxeprice)));

    }//GEN-LAST:event_pluschickendeluxActionPerformed

    private void minuschickendeluxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minuschickendeluxActionPerformed
        chickenburgerdeluxe--;
        if (chickenburgerdeluxe < 0) {
            JOptionPane.showMessageDialog(null, "Invalid option   ");
        } else {

            chickendelux.setText(" " + chickenburgerdeluxe + "   Price : " + (chickendeluxetotal = database.Mutli(chickenburgerdeluxe, (int) chickendeluxeprice)));
        }
    }//GEN-LAST:event_minuschickendeluxActionPerformed

    private void pluschickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pluschickenActionPerformed
        chickenburger++;

        chicken.setText(" " + chickenburger + "   Price : " + (chickentotal = database.Mutli(chickenburger, (int) chickenprice)));
    }//GEN-LAST:event_pluschickenActionPerformed

    private void minuschickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minuschickenActionPerformed
        chickenburger--;
        if (chickenburger < 0) {
            JOptionPane.showMessageDialog(null, "Invalid option   ");
        } else {

            chicken.setText(" " + chickenburger + "   Price : " + (chickentotal = database.Mutli(chickenburger, (int) chickenprice)));
        }
    }//GEN-LAST:event_minuschickenActionPerformed

    private void plusdoublebeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusdoublebeefActionPerformed
        bdouble++;

        doublebeefnum.setText(" " + bdouble + "   Price : " + (bdoubletotal = database.Mutli(bdouble, (int) bdoubleprice)));
    }//GEN-LAST:event_plusdoublebeefActionPerformed

    private void minusdoublebeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusdoublebeefActionPerformed
        bdouble--;
        if (bdouble < 0) {
            JOptionPane.showMessageDialog(null, "Invalid option   ");
        } else {

            doublebeefnum.setText(" " + bdouble + "   Price : " + (bdoubletotal = database.Mutli(bdouble, (int) bdoubleprice)));

        }
    }//GEN-LAST:event_minusdoublebeefActionPerformed

    private void Addtocart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Addtocart1ActionPerformed

        beef.setText(" " + bsingle + "    Pirce: " + (btotal = database.Mutli(bsingle, (int) bsingleprice)));

        doublebeef.setText(" " + bdouble + "   Price : " + (bdoubletotal = database.Mutli(bdouble, (int) bdoubleprice)));

        chik.setText(" " + chickenburger + "   Price : " + (chickentotal = database.Mutli(chickenburger, (int) chickenprice)));

        chikdelux.setText(" " + chickenburgerdeluxe + "   Price : " + (chickendeluxetotal = database.Mutli(chickenburgerdeluxe, (int) chickendeluxeprice)));

        totalview.setText(" " + (btotal + bdoubletotal + chickentotal + chickendeluxetotal));

        JOptionPane.showMessageDialog(null, "Items added to cart   ");

    }//GEN-LAST:event_Addtocart1ActionPerformed

    private void minusbeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusbeefActionPerformed

        bsingle--;
        if (bsingle < 0) {
            JOptionPane.showMessageDialog(null, "Invalid option   ");

        } else {

            singlebeef.setText(" " + bsingle + "    Pirce: " + (btotal = database.Mutli(bsingle, (int) bsingleprice)));
        }
    }//GEN-LAST:event_minusbeefActionPerformed

    private void plusbeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusbeefActionPerformed
        bsingle++;

        singlebeef.setText(" " + bsingle + "    Pirce: " + (btotal = database.Mutli(bsingle, (int) bsingleprice)));

    }//GEN-LAST:event_plusbeefActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        bsingle = 0;
        bdouble = 0;
        chickenburger = 0;
        chickenburgerdeluxe = 0;

        singlebeef.setText(" " + bsingle + "    Pirce: " + (btotal = database.Mutli(bsingle, (int) bsingleprice)));

        doublebeefnum.setText(" " + bdouble + "   Price : " + (bdoubletotal = database.Mutli(bdouble, (int) bdoubleprice)));

        chicken.setText(" " + chickenburger + "   Price : " + (chickentotal = database.Mutli(chickenburger, (int) chickenprice)));
        chickendelux.setText(" " + chickenburgerdeluxe + "   Price : " + (chickendeluxetotal = database.Mutli(chickenburgerdeluxe, (int) chickendeluxeprice)));

        beef.setText(" " + bsingle + "    Pirce: " + (btotal = database.Mutli(bsingle, (int) bsingleprice)));

        doublebeef.setText(" " + bdouble + "   Price : " + (bdoubletotal = database.Mutli(bdouble, (int) bdoubleprice)));

        chik.setText(" " + chickenburger + "   Price : " + (chickentotal = database.Mutli(chickenburger, (int) chickenprice)));

        chikdelux.setText(" " + chickenburgerdeluxe + "   Price : " + (chickendeluxetotal = database.Mutli(chickenburgerdeluxe, (int) chickendeluxeprice)));

        totalview.setText(" " + (btotal + bdoubletotal + chickentotal + chickendeluxetotal));

    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuandcart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuandcart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuandcart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuandcart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuandcart().setVisible(true);

            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addtocart1;
    private javax.swing.JButton Addtocart2;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel beef;
    private javax.swing.JLabel chicken;
    private javax.swing.JLabel chickendelux;
    private javax.swing.JLabel chik;
    private javax.swing.JLabel chikdelux;
    private javax.swing.JLabel doublebeef;
    private javax.swing.JLabel doublebeefnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton minusbeef;
    private javax.swing.JButton minuschicken;
    private javax.swing.JButton minuschickendelux;
    private javax.swing.JButton minusdoublebeef;
    private javax.swing.JButton paynow;
    private javax.swing.JButton plusbeef;
    private javax.swing.JButton pluschicken;
    private javax.swing.JButton pluschickendelux;
    private javax.swing.JButton plusdoublebeef;
    private javax.swing.JLabel singlebeef;
    private javax.swing.JLabel totalview;
    // End of variables declaration//GEN-END:variables
}
